image: alpine:latest

stages:
  - mirror

before_script:
  - apk add --no-cache git
  - git config --global user.name "ChaHyunHo"
  - git config --global user.email "chamym@naver.com"

mirror_to_github:
  stage: mirror
  script:
    - git remote add github https://ChaHyunHo:${GITHUB_TOKEN}@github.com/ChaHyunHo/spring-education-week1.git
    - git fetch origin main
    - git checkout -B main origin/main
    - git push -f github main
  only:
    - main
  tags:
    - mirror









